# Generated by Django 5.2.6 on 2025-09-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Computed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.IntegerField()),
                ("output", models.IntegerField()),
                ("time_computed", models.DateTimeField(null=True)),
            ],
        ),
    ]
